# Test snapshot
dependency_groups:
  Docker Images:
    - file: compose.yaml
      name: prettier-image
      datasource: docker
    - file: compose.yaml
      name: ansible-lint
      datasource: docker
  GitHub Releases:
    - file: roles/lazygit/tasks/main.yml
      name: lazygit
      datasource: github-releases
