# Renovate Dependencies Snapshot
# This file tracks all dependencies that Renovate should find
# Run ./scripts/update-renovate-snapshot.sh to update this file
# Last updated: 2026-02-01T17:30:00Z

# Total dependencies tracked
totalDependencies: 24

dependencies:
  # ==================== DOCKER IMAGES (6) ====================

  # renovate: datasource=docker depName=ghcr.io/bacluc/prettier-image
  - file: compose.yaml
    depName: prettier-image
    currentValue: "3.3.3"
    datasource: docker

  # renovate: datasource=docker depName=registry.gitlab.com/pipeline-components/ansible-lint
  - file: compose.yaml
    depName: ansible-lint
    currentValue: "amd64-469fada"
    datasource: docker

  # renovate: datasource=docker depName=registry.gitlab.com/pipeline-components/yamllint
  - file: compose.yaml
    depName: yamllint
    currentValue: "amd64-7487732"
    datasource: docker

  # renovate: datasource=docker depName=ghcr.io/fluxcd/flux-cli
  - file: roles/fluxcd/tasks/main.yml
    depName: flux-cli
    currentValue: "v2.2.3"
    datasource: docker

  # renovate: datasource=docker depName=ghcr.io/open-webui/open-webui
  - file: roles/openwebui/files/docker-compose.yml
    depName: open-webui
    currentValue: "v0.7.2"
    datasource: docker

  # renovate: datasource=docker depName=docker.io/projectsyn/commodore
  - file: roles/vshn_tools/tasks/main.yml
    depName: commodore
    currentValue: "v1.29.0"
    datasource: docker

  # ==================== GITHUB RELEASES (14) ====================

  # renovate: datasource=github-releases depName=gdraheim/docker-systemctl-replacement
  - file: .devcontainer/ansible/Dockerfile
    depName: docker-systemctl-replacement
    currentValue: "v1.5.9063"
    datasource: github-releases

  # renovate: datasource=github-releases depName=nvm-sh/nvm
  - file: .devcontainer/ansible/Dockerfile
    depName: nvm
    currentValue: "v0.40.0"
    datasource: github-releases

  # renovate: datasource=github-releases depName=leoafarias/fvm
  - file: roles/basic_utils/tasks/main.yml
    depName: fvm
    currentValue: "3.2.1"
    datasource: github-releases

  # renovate: datasource=github-releases depName=Homebrew/brew
  - file: roles/homebrew/tasks/main.yaml
    depName: homebrew
    currentValue: "4.6.14"
    datasource: github-releases

  # renovate: datasource=github-releases depName=jlandowner/helm-chartsnap
  - file: roles/kubectl/tasks/main.yml
    depName: helm-chartsnap
    currentValue: "0.6.0"
    datasource: github-releases

  # renovate: datasource=github-releases depName=databus23/helm-diff
  - file: roles/kubectl/tasks/main.yml
    depName: helm-diff
    currentValue: "3.12.5"
    datasource: github-releases

  # renovate: datasource=github-releases depName=itaysk/kubectl-neat
  - file: roles/kubectl/tasks/main.yml
    depName: kubectl-neat
    currentValue: "v2.0.4"
    datasource: github-releases

  # renovate: datasource=github-releases depName=robscott/kube-capacity
  - file: roles/kubectl/tasks/main.yml
    depName: kube-capacity
    currentValue: "v0.8.0"
    datasource: github-releases

  # renovate: datasource=github-releases depName=rajatjindal/kubectl-modify-secret
  - file: roles/kubectl/tasks/main.yml
    depName: kubectl-modify-secret
    currentValue: "v0.0.47"
    datasource: github-releases

  # renovate: datasource=github-releases depName=jesseduffield/lazygit
  - file: roles/lazygit/tasks/main.yml
    depName: lazygit
    currentValue: "0.58.0"
    datasource: github-releases

  # renovate: datasource=github-releases depName=nvm-sh/nvm
  - file: roles/nvm/tasks/main.yaml
    depName: nvm
    currentValue: "v0.40.3"
    datasource: github-releases

  # renovate: datasource=github-releases depName=vshn/emergency-credentials-receive
  - file: roles/vshn_emergency_credentials_receive/tasks/main.yml
    depName: emergency-credentials-receive
    currentValue: "1.2.1"
    datasource: github-releases

  # renovate: datasource=github-releases depName=vshn/appcat-cli
  - file: roles/vshn_tools/tasks/main.yml
    depName: appcat-cli
    currentValue: "0.5.0"
    datasource: github-releases

  # renovate: datasource=github-releases depName=vshn/k8ify
  - file: roles/vshn_tools/tasks/main.yml
    depName: k8ify
    currentValue: "2.3.0"
    datasource: github-releases

  # renovate: datasource=github-releases depName=zed-industries/zed
  - file: roles/zed/tasks/main.yml
    depName: zed
    currentValue: "v0.204.5"
    datasource: github-releases

  # ==================== GIT REFERENCES (3) ====================

  # renovate: datasource=git-refs depName=https://github.com/langchr86/git-tools.git
  - file: requirements.yml
    depName: git-tools
    currentValue: "09c14e2"
    datasource: git-refs

  # renovate: datasource=git-refs depName=https://github.com/gantsign/ansible-role-visual-studio-code.git
  - file: requirements.yml
    depName: ansible-role-visual-studio-code
    currentValue: "7.0.0"
    datasource: git-refs

  # renovate: datasource=git-refs depName=https://github.com/PeterMosmans/ansible-role-customize-gnome.git
  - file: requirements.yml
    depName: ansible-role-customize-gnome
    currentValue: "0.2.12"
    datasource: git-refs
