- src: "https://github.com/langchr86/git-tools.git"
  version: "09c14e2"
- src: "https://github.com/gantsign/ansible-role-visual-studio-code.git"
  version: "7.0.0"
- src: "https://github.com/PeterMosmans/ansible-role-customize-gnome.git"
  version: "0.2.12"
