- src: 'https://github.com/langchr86/git-tools.git'
  version: '6fc6898'
- src: 'https://github.com/langchr86/ansible-role-docmake.git'
  version: '27ed841'
- src: 'https://github.com/gantsign/ansible-role-intellij.git'
  version: '6.6.1'
- src: 'https://github.com/gantsign/ansible-role-visual-studio-code.git'
  version: '6.8.0'
- src: 'https://github.com/PeterMosmans/ansible-role-customize-gnome.git'
  version: '0.2.4'  
