---
- name: install okular
  become: true
  package:
    name: okular

- name: create gnome defaults file
  become: true
  file:
    path: /etc/gnome/defaults.list
    state: touch
    modification_time: preserve
    access_time: preserve

- name: set okular as default pdf viewer
  become: true
  lineinfile:
    dest: "/etc/gnome/defaults.list"
    regexp: "^application/pdf="
    line: "application/pdf=okular.desktop"
