---
- name: install okular
  become: true
  ansible.builtin.package:
    name: okular

- name: create gnome defaults file
  become: true
  ansible.builtin.file:
    path: /etc/gnome/defaults.list
    state: touch
    modification_time: preserve
    access_time: preserve
    mode: "u=rwx,go=rx"

- name: set okular as default pdf viewer
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/gnome/defaults.list"
    regexp: "^application/pdf="
    line: "application/pdf=okular.desktop"
