- name: Install keyrings directory
  become: true
  ansible.builtin.command:
    cmd: install -m 0755 -d /usr/share/keyrings
    creates: /usr/share/keyrings

- name: download key
  become: true
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: "/usr/share/keyrings/hashicorp-archive-keyring.asc"
    force: false
    mode: "ugo=r"
    timeout: 30

- name: get arch
  ansible.builtin.command: dpkg --print-architecture
  register: arch
  changed_when: false

- name: get release
  ansible.builtin.shell: . /etc/os-release && echo "$VERSION_CODENAME"
  register: os_release
  changed_when: false

- name: add hashicorp apt repository with signature
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch.stdout }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ os_release.stdout }} main"
    update_cache: true
    filename: hashicorp.list
