- name: Check if ansible ppa is already installed
  stat:
    path: ansible.apt_list_file
  register: apt_list_file_exists

- name: Add ansible ppa
  when: apt_list_file_exists.stat.exists is false
  become: true
  command: |
    sudo add-apt-repository -y ppa:ansible/ansible
