- name: Install basic tools
  become: true
  package:
    name: "{{ apt_packages.basic_tools }}"

- name: Set timezone to Europe/Zurich
  become: true
  timezone:
    name: Europe/Zurich

- name: Set locale to en_US.UTF-8
  become: true
  locale_gen:
    name: en_US.UTF-8

- name: Set default locale to en_US.UTF-8
  become: true
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"en_US.UTF-8\""

- name: Set lang to en_US.UTF-8
  become: true
  lineinfile: dest=/etc/default/locale
    regexp="LANG"
    line="LANG=\"en_US.UTF-8\""

- name: Install additional packages
  become: true
  package:
    name: "{{ apt_packages.additional_tools }}"
