---

- name: create java installation directory
  become: true
  file:
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    dest: '/opt/java'

- name: set facts for openjdk version
  set_fact:
    jdk_major_version: '17'
    jdk_minor_version: '0.3'
    jdk_build_number: '7'

- name: combine java version vars
  set_fact:
    jdk_version: '{{ jdk_major_version }}.{{ jdk_minor_version }}+{{ jdk_build_number }}'

- name: 'download jdk {{ jdk_version }}'
  become: true
  get_url:
    url: 'https://github.com/adoptium/temurin{{ jdk_major_version }}-binaries/releases/download/jdk-{{ jdk_major_version }}.{{ jdk_minor_version }}%2B{{ jdk_build_number }}/OpenJDK{{ jdk_major_version }}U-jdk_x64_linux_hotspot_{{ jdk_major_version }}.{{ jdk_minor_version }}_{{ jdk_build_number }}.tar.gz'
    dest: '/opt/java/jdk-{{ jdk_version }}.tar.gz'
    force: false
    use_proxy: true
    validate_certs: true
    mode: 'u=rw,go=r'

- name: install jdk {{ jdk_version }}
  become: true
  unarchive:
    src: '/opt/java/jdk-{{ jdk_version }}.tar.gz'
    remote_src: true
    dest: '/opt/java'
    owner: root
    group: root
    mode: 'o-w'
    creates: '/opt/java/jdk-{{ jdk_version }}/bin'

- name: set facts for openjdk locations
  set_fact:
    jdk_home: '/opt/java/jdk-{{ jdk_version }}'
