- name: Install psutil that is needed for dconf module below
  become: true
  apt:
    name: python3-psutil

- name: Install xfce-terminal
  become: true
  apt:
    name: xfce4-terminal

- name: define all gnome favorite apps
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['nemo.desktop', 'firefox.desktop', 'xfce4-terminal.desktop', 'code.desktop']"

- name: add german keyboard layouts
  dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'ch'), ('xkb', 'us')]"

- name: add shortcut for switching workspace down
  dconf:
    key: /org/gnome/desktop/wm/keybindings switch-to-workspace-down
    value: "['<Super>Page_Down', '<Control><Super>Down']"

- name: add shortcut for switching workspace left
  dconf:
    key: /org/gnome/desktop/wm/keybinding switch-to-workspace-left
    value: "['<Control><Super>Left']"

- name: add shortcut for switching workspace up
  dconf:
    key: /org/gnome/desktop/wm/keybinding switch-to-workspace-up
    value: "['<Control><Super>Up']"

- name: add shortcut for switching workspace right
  dconf:
    key: /org/gnome/desktop/wm/keybinding switch-to-workspace-right
    value: "['<Control><Super>Right']"
