- name: Install psutil that is needed for dconf module below
  become: true
  apt:
    name: python3-psutil

- name: Install xfce-terminal
  become: true
  apt:
    name: xfce4-terminal

- name: define all gnome favorite apps
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['nemo.desktop', 'chromium-browser.desktop', 'ghostty.desktop', 'code.desktop']"

- name: add german keyboard layouts
  dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'ch'), ('xkb', 'us')]"

# to dump the current settings:
# gsettings list-recursively org.gnome.desktop.wm.keybindings
# gsettings list-recursively org.gnome.mutter.keybindings
- name: configure keyboard shortcuts
  set_fact:
    gnome_shortcuts:
      - schema: "org.gnome.desktop.wm.keybindings"
        key: "switch-to-workspace-right"
        value: "['<Control><Super>Right']"
        description: "add shortcut for switching workspace right"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "switch-to-workspace-down"
        value: "['<Control><Super>Down']"
        description: "add shortcut for switching workspace down"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "switch-to-workspace-left"
        value: "['<Control><Super>Left']"
        description: "add shortcut for switching workspace left"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "switch-to-workspace-up"
        value: "['<Control><Super>Up']"
        description: "add shortcut for switching workspace up"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "move-to-workspace-right"
        value: "['<Control><Shift><Alt>Right']"
        description: "add shortcut for moving window to monitor right"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "move-to-workspace-down"
        value: "['<Control><Shift><Alt>Down']"
        description: "add shortcut for moving window to monitor down"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "move-to-workspace-left"
        value: "['<Control><Shift><Alt>Left']"
        description: "add shortcut for moving window to monitor left"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "move-to-workspace-up"
        value: "['<Control><Shift><Alt>Up']"
        description: "add shortcut for moving window to monitor up"

      - schema: "org.gnome.mutter.keybindings"
        key: "toggle-tiled-right"
        value: "['<Super>Right']"
        description: "set shortcut for tiling window right"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "unmaximize"
        value: "['<Super>Down']"
        description: "add minimize shortcut"

      - schema: "org.gnome.mutter.keybindings"
        key: "toggle-tiled-left"
        value: "['<Super>Left']"
        description: "set shortcut for tiling window left"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "maximize"
        value: "['<Super>Up']"
        description: "add maximize shortcut"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "move-to-monitor-down"
        value: "['<Shift><Super>Down']"
        description: "add shortcut for moving window to monitor down"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "move-to-monitor-left"
        value: "['<Shift><Super>Left']"
        description: "add shortcut for moving window to monitor left"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "move-to-monitor-right"
        value: "['<Shift><Super>Right']"
        description: "add shortcut for moving window to monitor right"

      - schema: "org.gnome.desktop.wm.keybindings"
        key: "move-to-monitor-up"
        value: "['<Shift><Super>Up']"
        description: "add shortcut for moving window to monitor up"

- name: set dconf shortcuts
  command: 'gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"'
  loop: "{{ gnome_shortcuts }}"
  loop_control:
    label: "{{ item.description }}\n"

- name: disable gpaste shortcuts
  when: "'gpaste-2' in apt_packages.additional_tools"
  block:
    - name: reset all these shortcuts with gsettings
      command: "gsettings reset {{ item.schema }} {{ item.key }}"
      loop:
        - { schema: "org.gnome.GPaste", key: "history-name" }
        - { schema: "org.gnome.GPaste", key: "images-support" }
        - { schema: "org.gnome.GPaste", key: "launch-ui" }
        - { schema: "org.gnome.GPaste", key: "make-password" }
        - { schema: "org.gnome.GPaste", key: "pop" }
        - { schema: "org.gnome.GPaste", key: "show-history" }
        - { schema: "org.gnome.GPaste", key: "sync-clipboard-to-primary" }
        - { schema: "org.gnome.GPaste", key: "sync-primary-to-clipboard" }
        - { schema: "org.gnome.GPaste", key: "upload" }
