- name: Install psutil that is needed for dconf module below
  become: true
  apt:
    name: python3-psutil

- name: Install xfce-terminal
  become: true
  apt:
    name: xfce4-terminal

- name: define all gnome favorite apps
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['nemo.desktop', 'firefox.desktop', 'xfce4-terminal.desktop', 'code.desktop']"

- name: add german keyboard layouts
  dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'ch'), ('xkb', 'us')]"
