- name: Install DKMS and virtualbox additions
  become: true
  package:
    name:
      - dkms
      - virtualbox-guest-dkms
      - virtualbox-guest-utils
      - virtualbox-guest-x11

- name: Add user to vboxsf group to have access to bind mounts
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    append: true
    groups: vboxsf
