- name: Install ssh tools
  become: true
  package:
    name:
      - xorg
      - xauth
      - openssh-client
      - openssh-server

- name: Add authorized keys
  become: true
  authorized_key:
    user: "{{ ansible_env.USER }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ ssh_pub_files }}"
