- name: vshn-tools
  when: enable_vshn_tools | default(false)
  block:
    - name: vshn_tools print var
      ansible.builtin.debug:
        var: vshn_tools

    - name: set defaults for vshn_tools role
      ansible.builtin.set_fact:
        vshn_tools_defaults:
          # renovate: datasource=github-releases depName=vshn/appcat-cli
          appcat_cli_version: "0.5.0"
          appcat_cli_checksum: 2141bf312b56ff7baf7727a98bbe0488dab7769162fb88e63255209e3e8140f1
          # renovate: datasource=github-releases depName=vshn/k8ify
          k8ify_version: "2.5.0"
          k8ify_checksum: f3605d34439c0bef36930c71ad2b066acc0ba821e68c98e764fffc1a66dcc3b9
          # renovate: datasource=github-releases depName=jsonnet-bundler/jsonnet-bundler
          jsonnet_bundler_version: "0.6.0"
          jsonnet_bundler_checksum: sha256:78e54afbbc3ff3e0942b1576b4992277df4f6beb64cddd58528a76f0cd70db54

          commodore_python_version: 3.12

    - name: set facts for vshn_tools role
      ansible.builtin.set_fact:
        vshn_tools: "{{ vshn_tools_defaults | combine((vshn_tools | default({})), recursive=true) }}"

    - name: ensure ~/bin directory exists
      ansible.builtin.file:
        path: "~/bin"
        state: directory
        mode: "u=rwx,go=rx"

    - name: install appcat-cli
      ansible.builtin.include_role:
        name: github_release_binary
      vars:
        url: "https://github.com/vshn/appcat-cli/releases/download/v{{ vshn_tools.appcat_cli_version }}/appcat-cli_{{ vshn_tools.appcat_cli_version }}_linux_amd64.tar.gz"
        binary_name: appcat-cli
        binary_checksum: "{{ vshn_tools.appcat_cli_checksum }}"

    - name: install k8ify
      ansible.builtin.include_role:
        name: github_release_binary
      vars:
        url: "https://github.com/vshn/k8ify/releases/download/v{{ vshn_tools.k8ify_version }}/k8ify_{{ vshn_tools.k8ify_version }}_linux_amd64.tar.gz"
        binary_name: k8ify
        binary_checksum: "{{ vshn_tools.k8ify_checksum }}"

    - name: setup alias for commodore
      ansible.builtin.blockinfile:
        path: "~/.bash_aliases"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: commodore alias"
        state: absent
        block: |
          alias commodore='docker run \
              --rm \
              --user="${UID}" \
              --volume "${PWD}:/app/data" \
              --workdir /app/data \
              projectsyn/commodore:${COMMODORE_VERSION:=v1.29.0}'

    - name: install jsonnet-bundler
      ansible.builtin.get_url:
        url: "https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v{{ vshn_tools.jsonnet_bundler_version }}/jb-linux-amd64"
        dest: "~/bin/jb"
        mode: "u=rwx,go=rx"
        checksum: "{{ vshn_tools.jsonnet_bundler_checksum }}"

    - name: install commodore
      ansible.builtin.shell:
        cmd: |
          /home/{{ user }}/bin/uv tool install --python=python{{ vshn_tools_defaults.commodore_python_version }} --python-preference=system syn-commodore
        creates: "~/.local/bin/commodore"

    - name: set default lieutenant api url for bash
      ansible.builtin.blockinfile:
        path: "~/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: add commodore default api url"
        block: |
          export COMMODORE_API_URL=https://api.syn.vshn.net

    - name: set default lieutenant api url for zsh
      when: enable_zsh | default(false)
      ansible.builtin.blockinfile:
        path: "~/.zshrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: add commodore default api url"
        block: |
          export COMMODORE_API_URL=https://api.syn.vshn.net

    - name: add update script
      become: true
      ansible.builtin.copy:
        content: |
          #!/bin/sh

          su {{ user }} -c "/home/{{ user }}/bin/uv tool upgrade syn-commodore"
        dest: "{{ update_packages_script.dir }}/commodore-upgrade"
        mode: "u=rwx,go=rx"

    - name: add bash autocomplete for bash
      ansible.builtin.blockinfile:
        path: "~/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: add autocomplete for commodore"
        block: |
          source <(_COMMODORE_COMPLETE=zsh_source commodore)

    - name: add zsh autocomplete for zsh
      when: enable_zsh | default(false)
      ansible.builtin.blockinfile:
        path: "~/.zshrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: add autocomplete for commodore"
        block: |
          source <(_COMMODORE_COMPLETE=zsh_source commodore)
