- name: git-lfs
  when: enable_git_lfs | default(false)
  block:
    - name: set defaults for git_lfs role
      ansible.builtin.set_fact:
        git_lfs_defaults:
          # renovate: datasource=github-releases depName=git-lfs/git-lfs
          git_lfs_version: "3.7.1"
          git_lfs_checksum: "1c0b6ee5200ca708c5cebebb18fdeb0e1c98f1af5c1a9cba205a4c0ab5a5ec08"

    - name: set facts for git_lfs role
      ansible.builtin.set_fact:
        git_lfs: "{{ git_lfs_defaults | combine((git_lfs | default({})), recursive=true) }}"

    - name: install git-lfs
      ansible.builtin.include_role:
        name: github_release_binary
      vars:
        url: "https://github.com/git-lfs/git-lfs/releases/download/v{{ git_lfs.git_lfs_version }}/git-lfs-linux-amd64-v{{ git_lfs.git_lfs_version }}.tar.gz"
        binary_name: git-lfs
        binary_checksum: "{{ git_lfs.git_lfs_checksum }}"
        tar_strip_components: 1
