- name: "customize gnome"
  when: enable_customize_gnome | default(false)
  block:
    - name: "install gnome extensions app"
      when: basic_utils.enable_keepassxc | default(false)
      flatpak:
        name:
          - org.gnome.Extensions
