# From: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions
- name: "Install azure-cli"
  when: enable_azure_cli | default(false)
  tags: azure_cli
  block:
    - name: "check if azure cli is installed"
      stat:
        path: "{{ homebrew_path }}/az"
      register: azure_cli_installed

    - name: "install azure cli"
      when: azure_cli_installed.stat.exists is false
      command: |
        {{ homebrew_path }}/brew install azure-cli

    - name: "check if kubelogin is installed"
      stat:
        path: "{{ homebrew_path }}/kubelogin"
      register: azure_cli_kubelogin_installed

    - name: "install kubelogin"
      when: azure_cli_kubelogin_installed.stat.exists is false
      command: |
        {{ homebrew_path }}/brew install azure-cli Azure/kubelogin/kubelogin

    - name: Add aliases
      lineinfile: dest="~/.bash_aliases"
        line="{{ item.line }}"
        regexp="{{ item.regexp }}"
        state=present
        insertafter=EOF
        create=True
        mode="u+rw"
      with_items:
        - {
            regexp: "^alias azl=",
            line: "alias azl='az login --use-device-code'",
          }
