- name: windows print var
  ansible.builtin.debug:
    var: windows

- name: install scoop packages
  shell: |
    scoop install {{ windows.scoop_packages | join(' ') }}

- name: Setup user bin dir
  file:
    path: "~/bin"
    state: directory
    mode: "u=rwx,go=rx"

- name: source user bin dir
  ansible.builtin.blockinfile:
    path: "~/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: bin of user"
    block: |
      export PATH="/home/{{ user }}/bin:$PATH"

- name: setup maven proxy
  template:
    src: mvn-proxy.j2
    dest: "~/bin/mvn"
    mode: "u+rwx"

- name: setup git proxy
  template:
    src: git-proxy.j2
    dest: "~/bin/git"
    mode: "u+rwx"
