- name: Install tmux tools
  become: true
  package:
    name:
      - tmux

- name: Add tmux config
  copy:
    src: .tmux.conf
    dest: "~/"
    mode: "u+rw"

- name: Ensure Unix line endings
  replace:
    path: "{{ item }}"
    regexp: "\r\n"
    replace: "\n"
  with_items:
    - "~/.tmux.conf"
