- name: Install dependency for CLion markdown plugin
  become: true
  package:
    name:
      - openjfx

- name: Create directories for CLion
  file:
    path: "{{ item }}"
    state: directory
    mode: "u+rw"
  with_items:
    - "{{ clion_download_directory }}"
    - "{{ clion_install_directory }}"

- name: Install CLion
  unarchive:
    copy: false
    src: "{{ clion_download_url }}"
    dest: "{{ clion_install_directory }}"
    creates: "{{ clion_location }}/bin/clion.sh"

- name: Add clion alias for all user profiles
  become: true
  lineinfile:
    dest="/etc/profile.d/clion.sh"
    line="alias clion='{{ clion_location }}/bin/clion.sh &>/dev/null'"
    regexp='^alias clion='
    state=present
    insertafter=EOF
    create=True
    mode="ugo+rw"

- name: create local .local/share/applications folder
  file:
    dest: "{{ ansible_env.HOME }}/.local/share/applications/"
    state: directory
    mode: "u+rw"

- name: Add clion desktop file
  template:
    dest: "{{ ansible_env.HOME }}/.local/share/applications/jetbrains-clion.desktop"
    src: "jetbrains-clion.desktop"
    mode: "u+rw"

- name: Define a high number of inotify watches
  become: true
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
