name: "Run provisioning on ubuntu"
"on":
  push:
  pull_request:
  schedule:
    - cron: "42 4 * * 0"
  workflow_dispatch:

jobs:
  pyinfra_lint:
    name: "pyinfra lint"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: "install dependencies"
        run: uv sync --frozen --all-extras

      - name: "pytest"
        run: uv run pytest

      - name: "ruff check"
        run: uv run ruff check .

      - name: "mypy"
        run: uv run mypy .

      - name: "run prettier"
        run: |
          # renovate: datasource=docker depName=ghcr.io/bacluc/prettier-image/prettier-image
          prettier_image_version="3.8.4"
          docker run --rm -v $PWD:/workdir -w /workdir -u $UID ghcr.io/bacluc/prettier-image/prettier-image:${prettier_image_version}
          git diff --exit-code

  run_pyinfra:
    name: "Run pyinfra on ubuntu"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: "install dependencies"
        run: uv sync --frozen

      - name: "run pyinfra"
        run: uv run scripts/run_pyinfra_local.py

      - name: "run update-script"
        run: sudo update-script

      - name: "run cleanup-script"
        run: sudo cleanup-script

      - name: "run pyinfra a second time"
        run: uv run scripts/run_pyinfra_local.py
