name: "Run provisioning on ubuntu"
"on":
  push:
  pull_request:
  schedule:
    - cron: "42 4 * * 0"
  workflow_dispatch:

jobs:
  run_provisioning:
    name: "Run provisioning on ubuntu"
    runs-on: ubuntu-22.04
    steps:
      - name: "uninstall homebrew"
        run: |
          sudo rm -rf /home/linuxbrew

      - name: "install correct ansible"
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ansible/ansible
          sudo apt-get update
          sudo apt-get purge ansible -y
          sudo apt-get install -y ansible
          ansible --version

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: "run provisioning"
        run: |
          cp ci-inventory.yaml inventory/local.yaml
          ./provision.sh

      - name: "test update script"
        run: sudo update-script

      - name: "print journalctl"
        if: always()
        run: journalctl

      - name: "run provisioning a second time"
        run: |
          ./provision.sh

  check_format:
    name: "check format"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: "check format"
        run: |
          docker compose run --rm prettier
          git diff --exit-code

  lint:
    name: "lint"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - run: docker compose run --rm --quiet-pull yamllint

      - run: docker compose run --rm --quiet-pull ansible-lint
